# Generated by Django 3.0.6 on 2020-07-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='number_of_samples',
            field=models.IntegerField(null=True),
        ),
    ]
