# Generated by Django 3.0.6 on 2020-07-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
        ('shopping_cart', '0003_auto_20200715_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.Profile'),
        ),
    ]
