# Generated by Django 3.0.6 on 2020-06-01 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0014_profile'),
        ('shopping_cart', '0003_remove_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.Profile'),
        ),
    ]
