# Generated by Django 3.0.6 on 2020-06-04 01:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('Webapp', '0016_profile_services'),
        ('shopping_cart', '0004_order_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderServices',
        ),
    ]
