# Generated by Django 3.0.6 on 2020-06-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0016_profile_services'),
        ('shopping_cart', '0005_auto_20200604_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.TraininService')),
            ],
        ),
        migrations.CreateModel(
            name='OthersItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.OthersService')),
            ],
        ),
        migrations.CreateModel(
            name='OrderServicesTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='Webapp.TraininService')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderServicesOthers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='Webapp.OthersService')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderServicesNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='Webapp.FoodNutritionService')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutritionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webapp.FoodNutritionService')),
            ],
        ),
    ]
