# Generated by Django 3.0.6 on 2020-06-04 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('contact_number', models.IntegerField(null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('Organisation_name', models.CharField(blank=True, max_length=500)),
                ('Address', models.CharField(blank=True, max_length=256)),
                ('Postcode_or_zip_code', models.CharField(blank=True, max_length=128)),
                ('Town_or_City', models.CharField(blank=True, max_length=128)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ManyToManyField(blank=True, to='Webapp.Services')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.CharField(blank=True, default='OrderNo', max_length=50)),
                ('Date_recieved', models.DateTimeField(auto_now_add=True)),
                ('No_of_Samples', models.IntegerField(default=1)),
                ('Sample_Type', models.CharField(max_length=99, null=True)),
                ('Sample_Reciever', models.CharField(blank=True, max_length=128)),
                ('Analyis_Required', models.CharField(choices=[('Unknown', 'Unknown'), ('Sample Milling', 'Sample Milling'), ('Protein', 'Protein'), ('Aflatoxin', 'Aflatoxin'), ('Multimycotoxin', 'Multimycotoxin'), ('Primary Amino Acids', 'Primary Amino Acids'), ('Water soluble vitamin', 'Water soluble vitamin'), ('Fat soluble vitamins', 'Fat soluble vitamins'), ('Tannins', 'Tannins'), ('DM content', 'DM content'), ('Total free phenolics', 'Total free phenolics'), ('phytic acid', 'phytic acid'), ('total oxalate', 'total oxalate'), ('Crude fat', 'Crude fat'), ('Crude fiber', 'Crude fiber'), ('Mineral analysis (Fe, Zn, Mg, Ca, Mn, Co, Al, K, Na)', 'Mineral analysis (Fe, Zn, Mg, Ca, Mn, Co, Al, K, Na)')], default='Unknown', max_length=256)),
                ('Remarks', models.TextField()),
                ('Stage', models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Recieved', 'Recieved'), ('Extracted', 'Extracted'), ('QCd', 'QCd'), ('Reported', 'Reported')], default='Ordered', max_length=128)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
