# Generated by Django 3.0.6 on 2020-05-12 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.CharField(blank=True, default='OrderNo', max_length=50)),
                ('Date_recieved', models.DateTimeField(auto_now_add=True)),
                ('Client', models.CharField(default='Client name', max_length=256)),
                ('No_of_Samples', models.IntegerField(default=1)),
                ('Sample_Type', models.CharField(max_length=99, null=True)),
                ('Sample_Reciever', models.CharField(blank=True, max_length=128)),
                ('Analyis_Required', models.CharField(choices=[('Unknown', 'Unknown'), ('Sample Milling', 'Sample Milling'), ('Protein', 'Protein'), ('Aflatoxin', 'Aflatoxin'), ('Multimycotoxin', 'Multimycotoxin'), ('Primary Amino Acids', 'Primary Amino Acids'), ('Water soluble vitamin', 'Water soluble vitamin'), ('Fat soluble vitamins', 'Fat soluble vitamins'), ('Tannins', 'Tannins'), ('DM content', 'DM content')], default='Unknown', max_length=256)),
                ('Remarks', models.TextField()),
                ('Stage', models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Recieved', 'Recieved'), ('Extracted', 'Extracted'), ('QCd', 'QCd'), ('Reported', 'Reported')], default='Ordered', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('contact_number', models.PositiveIntegerField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('Organisation_name', models.CharField(blank=True, max_length=500)),
                ('Address', models.CharField(blank=True, max_length=256)),
                ('Postcode_or_zip_code', models.CharField(blank=True, max_length=128)),
                ('Town_or_City', models.CharField(blank=True, max_length=128)),
                ('Country', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
