# Generated by Django 3.0.6 on 2020-06-07 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('contact_number', models.IntegerField(null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('Organisation_name', models.CharField(blank=True, max_length=500)),
                ('Address', models.CharField(blank=True, max_length=256)),
                ('Postcode_or_zip_code', models.CharField(blank=True, max_length=128)),
                ('Town_or_City', models.CharField(blank=True, max_length=128)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
