# Generated by Django 3.0.5 on 2020-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Number', models.CharField(default='order number', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Date_recieved', models.DateTimeField(auto_now_add=True)),
                ('Client', models.CharField(default='Client name', max_length=256)),
                ('Client_Address', models.TextField()),
                ('Sample_Type', models.CharField(max_length=99, null=True)),
                ('Sample_Reciever', models.CharField(max_length=128)),
                ('Analyis_Required', models.IntegerField(choices=[('Unknown', 'Unknown'), ('Sample Milling', 'Sample Milling'), ('Protein', 'Protein'), ('Aflatoxin', 'Aflatoxin'), ('Aflatoxin', 'Aflatoxin'), ('Multimycotoxin', 'Multimycotoxin'), ('Primary Amino Acids', 'Primary Amino Acids'), ('Water soluble vitamin', 'Water soluble vitamin'), ('Fat soluble vitamins', 'Fat soluble vitamins'), ('Tannins', 'Tannins'), ('DM content', 'DM content')], default='Unknown')),
                ('Remarks', models.TextField()),
                ('Stage', models.IntegerField(choices=[(0, 'Ordered'), (1, 'Accepted'), (2, 'Recieved'), (3, 'Extracted'), (4, 'QCd'), (5, 'Reported')], default=0)),
            ],
        ),
    ]
