# Generated by Django 3.0.6 on 2020-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
