# Generated by Django 3.0.6 on 2020-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_auto_20200512_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
