# Generated by Django 3.0.5 on 2020-04-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
