# Generated by Django 3.0.6 on 2020-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_auto_20200512_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Analyis_Required',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Sample Milling', 'Sample Milling'), ('Protein', 'Protein'), ('Aflatoxin', 'Aflatoxin'), ('Multimycotoxin', 'Multimycotoxin'), ('Primary Amino Acids', 'Primary Amino Acids'), ('Water soluble vitamin', 'Water soluble vitamin'), ('Fat soluble vitamins', 'Fat soluble vitamins'), ('Tannins', 'Tannins'), ('DM content', 'DM content'), ('Total free phenolics', 'Total free phenolics'), ('phytic acid', 'phytic acid'), ('total oxalate', 'total oxalate'), ('Crude fat', 'Crude fat'), ('Crude fiber', 'Crude fiber'), ('Mineral analysis (Fe, Zn, Mg, Ca, Mn, Co, Al, K, Na)', 'Mineral analysis (Fe, Zn, Mg, Ca, Mn, Co, Al, K, Na)')], default='Unknown', max_length=256),
        ),
    ]
