# Generated by Django 3.0.5 on 2020-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_auto_20200422_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Analyis_Required',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Sample Milling', 'Sample Milling'), ('Protein', 'Protein'), ('Aflatoxin', 'Aflatoxin'), ('Multimycotoxin', 'Multimycotoxin'), ('Primary Amino Acids', 'Primary Amino Acids'), ('Water soluble vitamin', 'Water soluble vitamin'), ('Fat soluble vitamins', 'Fat soluble vitamins'), ('Tannins', 'Tannins'), ('DM content', 'DM content')], default='Unknown', max_length=256),
        ),
    ]
