# Generated by Django 3.0.6 on 2020-05-22 11:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_auto_20200521_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
