# Generated by Django 3.0.3 on 2020-04-29 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webapp', '0008_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.PositiveIntegerField()),
                ('Organisation_name', models.TextField(blank=True)),
                ('Address', models.CharField(blank=True, max_length=128)),
                ('Town_or_City', models.CharField(blank=True, max_length=128)),
                ('Postcode_or_zip_code', models.CharField(blank=True, max_length=128)),
                ('Country', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
