# Generated by Django 3.0.3 on 2020-04-29 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webapp', '0009_auto_20200429_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfileInfo',
        ),
    ]
