# Generated by Django 3.0.3 on 2020-04-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_auto_20200429_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Client_Address',
        ),
        migrations.AddField(
            model_name='order',
            name='No_of_samples',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Number',
            field=models.CharField(blank=True, default=0, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
