# Generated by Django 3.0.3 on 2020-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0014_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='Client_Name',
            field=models.CharField(default='Client name', max_length=256),
        ),
    ]
