# Generated by Django 3.0.3 on 2020-04-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0015_auto_20200430_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Client_Name',
            new_name='Client',
        ),
    ]
