# Generated by Django 3.0.3 on 2020-04-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0018_auto_20200430_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='No_of_samples',
            new_name='No_of_Samples',
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Number',
            field=models.CharField(blank=True, default='order number', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
