# Generated by Django 3.0.3 on 2020-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0019_auto_20200430_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Number',
            field=models.CharField(blank=True, default=0, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
