# Generated by Django 3.0.3 on 2020-04-30 11:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0020_auto_20200430_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=256),
        ),
    ]
