# Generated by Django 3.0.3 on 2020-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0024_auto_20200430_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Number',
            field=models.CharField(blank=True, default='OrderNo', max_length=50, primary_key=True, serialize=False),
        ),
    ]
